# Generated by Django 3.2.17 on 2023-04-25 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_address', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
    ]
