[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.http.redirections]
      [entryPoints.http.http.redirections.entryPoint]
        to = "https"
        scheme = "https"
        permanent = true

  [entryPoints.https]
    address = ":443"
    [entryPoints.https.http.tls]

[api]
  dashboard = true

[providers.docker]
  watch = true
  network = "root_default" # Aqui foi atualizado o nome da rede.
  exposedByDefault = false

[certificatesResolvers.http.acme]
  email = "${EMAIL}"
  storage = "acme.json"
  [certificatesResolvers.http.acme.httpChallenge]
    entryPoint = "http"

