# Generated by Django 3.2.17 on 2023-04-25 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hourservice',
            options={'verbose_name': 'Horário de Atendimento', 'verbose_name_plural': 'Horário de Atendimento'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
    ]
