# Generated by Django 3.2.17 on 2023-04-25 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_budget', '0002_rename_owner_expense_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'Controle de Gastos', 'verbose_name_plural': 'Controle de Gastos'},
        ),
    ]
