# Generated by Django 3.2.17 on 2023-04-17 16:35

import app_schedule.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AddField(
            model_name='schedule',
            name='protocol',
            field=models.CharField(default=app_schedule.models.generate_protocol, max_length=21, unique=True, verbose_name='Protocolo'),
        ),
    ]
