# Generated by Django 3.2.17 on 2023-04-17 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_schedule', '0002_auto_20230417_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Schedule', 'verbose_name_plural': 'Schedules'},
        ),
    ]
