# Generated by Django 3.2.17 on 2023-04-17 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_employees', '0001_initial'),
        ('app_schedule', '0004_alter_schedule_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_employees.employee', verbose_name='Mecânico'),
        ),
    ]
