# Generated by Django 3.2.17 on 2023-04-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_schedule', '0006_auto_20230417_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='employee',
        ),
        migrations.AddField(
            model_name='schedule',
            name='mechanic',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mecânico'),
        ),
    ]
