# Generated by Django 3.2.17 on 2023-04-17 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_employees', '0001_initial'),
        ('app_schedule', '0007_auto_20230417_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='mechanic',
        ),
        migrations.AddField(
            model_name='schedule',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_employees.employee', verbose_name='Mecânico'),
        ),
    ]
