# Generated by Django 3.2.17 on 2023-04-17 16:25

import app_history.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_schedule', '0001_initial'),
        ('app_employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Exclusão')),
                ('service_status', models.CharField(choices=[('pending', 'Pendente'), ('started', 'Iniciado'), ('ongoing', 'Em andamento'), ('finished', 'Finalizado')], default='pending', max_length=50)),
                ('service_image', models.ImageField(blank=True, null=True, upload_to=app_history.models.get_file_path)),
                ('service_video', models.FileField(blank=True, null=True, upload_to=app_history.models.get_video_path)),
                ('service_observation', models.TextField(blank=True, null=True)),
                ('vehicle_status', models.CharField(choices=[('pending', 'Pendente'), ('started', 'Iniciado'), ('ongoing', 'Em andamento'), ('finished', 'Finalizado')], default='pending', max_length=50)),
                ('service_time', models.DurationField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='app_employees.employee')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='app_schedule.schedule')),
            ],
            options={
                'verbose_name': 'Serviço agendado',
                'verbose_name_plural': 'Serviços agendados',
            },
        ),
    ]
