# Generated by Django 3.2.17 on 2023-03-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledservice',
            name='service_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
