# Generated by Django 3.2.17 on 2023-04-17 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledservice',
            options={'verbose_name': 'Histórico de Agendamento', 'verbose_name_plural': 'Histórico de Agendamentos'},
        ),
    ]
