# Generated by Django 3.2.17 on 2023-04-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_history', '0003_scheduledservice_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledservice',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledservice',
            name='problem_found',
            field=models.TextField(blank=True, null=True),
        ),
    ]
