# Generated by Django 3.2.17 on 2023-04-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_history', '0004_auto_20230417_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledservice',
            name='protocol',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
