# Generated by Django 3.2.17 on 2023-04-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_history', '0005_alter_scheduledservice_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledservice',
            name='service_status',
            field=models.CharField(choices=[('', '----------------'), ('pending', 'Pendente'), ('started', 'Iniciado'), ('ongoing', 'Em andamento'), ('finished', 'Finalizado')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduledservice',
            name='vehicle_status',
            field=models.CharField(choices=[('', '----------------'), ('pending', 'Pendente'), ('started', 'Iniciado'), ('ongoing', 'Em andamento'), ('finished', 'Finalizado')], default='pending', max_length=50),
        ),
    ]
